spring.application.name=marketplace-la-u
server.port=8080

spring.datasource.url=jdbc:mysql://api.lauapp.es:3306/db_laumarket
spring.datasource.username=dev_laumarket
spring.datasource.password=laumarket123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update